<a href="https://colab.research.google.com/github/yonalex09/Analisis_de_datos/blob/main/Tercer_analisis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

url = "https://raw.githubusercontent.com/yonalex09/Analisis_de_datos/main/Sample%20-%20Superstore.csv"
df = pd.read_csv(url,encoding='ISO-8859-1')

print("

Agrupammos por region y extraemos la media de los valores cuantitativos\n\n")
group = df.groupby('Region')
group.describe()
group.mean()

Agrupammos por region y extraemos la media de los valores cuantitativos

              Row ID   Postal Code       Sales  Quantity  Discount     Profit
Region
Central  5030.547998  65340.572536  215.772661  3.779595  0.240353  17.092709
East     4941.685042  17616.466994  238.336110  3.728230  0.145365  32.135808
South    5069.935185  34490.772840  241.803645  3.832716  0.147253  28.857673
West     4986.524508  91707.696534  226.493233  3.829535  0.109335  33.849032